### ISSUE TITLE
Add todomvc or more complex/real-life example

### ISSUE THREAD

**Issue by hwclass** [zaiste/huncwot#36]
Hi @zaiste,

Firstly, I really like the idea behind this framework. If it evolves with the community around itself, we'll see interesting results for the framework in the near future, I think. Good work, @zaiste.

Maybe have an example of more complex usage of huncwot with a todo app or something would be nice. If no one is volunteer, I would be on it.

Cheers

Baris

**Comment by zaiste** [comment]
@hwclass You are absolutely right, the real-life is a must-have. About 2 months ago I did a small workshop about Huncwot to non-programmers. 

Here's the thing we created: https://github.com/zaiste/huncwot-stories 

It's slightly outdated as I switched from Redux to MobX, but I plan to have a nice working example based on that. Any help would be appreciated!

**Comment by hwclass** [comment]
I would also hope to help you, just let's align with where I may begin.. ;)

**Comment by zaiste** [comment]
@hwclass I've just added an example of a simple todo app written using GraphQL. I'd be happy to have your feedback on it https://github.com/zaiste/huncwot-todo-graphql

**Comment by zaiste** [comment]
Here's another comprehensive example app that evolves along with the framework: https://github.com/zaiste/huncwot-example-app
