### ISSUE TITLE
Unrecognized lasso tag

### ISSUE THREAD

**Issue by seangates** [zaiste/huncwot#40]
Currently, I'm getting the following error after creating a new `huncwot` project from the CLI using `huncwot new <folder-name>`:

```
An error occurred while trying to compile template at path "/path/name/to/my/project/node_modules/huncwot/components/include-stylesheets.marko". Error(s) in template:
1) [node_modules/huncwot/components/include-stylesheets.marko:1:0] Unrecognized tag: lasso-head - More details: https://github.com/marko-js/marko/wiki/Error:-Unrecognized-Tag
```

**Node version:** v8.9.3

## Steps to reproduce:
1. Create a new project using `huncwot new <folder-name>`, then `cd <folder-name>`
2. Start the new project: `huncwot server`
3. Load the page in a browser: http://localhost:5544/

**Comment by zaiste** [comment]
@seangates thanks! I've just published `0.18.3`. It should resolve your issue. There was some dependency problem with `marko-path-router`

**Comment by seangates** [comment]
Great! I’ll give it a shot soon.

**Comment by seangates** [comment]
Tried it, but didn't work. So, I tried a couple things in the `package.json` and this seemed to do the trick:
```
  "dependencies": {
    "@lasso/marko-taglib": "^1.0.9",
    "huncwot": "^0.18.3",
    "knex": "latest",
    "lasso": "latest",
    "lasso-marko": "latest",
    "marko": "latest",
    "marko-path-router": "^0.5.0",
    "mobx": "latest",
    "sqlite3": "latest"
  },
```

**Comment by seangates** [comment]
It worked. Sorry for the delayed response (I’ve been down with a nasty cold).

**Comment by seangates** [comment]
Yeah, I'm not sure what made it fix. I can try some different combinations (once I feel better from a nasty cold).

**Comment by seangates** [comment]
Okay, it works when I remove `@lasso/marko-taglib`. Things now look like:

```
  "dependencies": {
    "huncwot": "^0.18.3",
    "knex": "latest",
    "lasso": "latest",
    "lasso-marko": "latest",
    "marko": "latest",
    "marko-path-router": "^0.5.0",
    "mobx": "latest",
    "sqlite3": "latest"
  },
```

Thanks for your help!
